version: "3"
services:
    mysql:
        build: api/mysql
        command: --default-authentication-plugin=mysql_native_password --secure-file-priv=""
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: mydatabase
        ports:
            - "3306:3306"
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$DB_USERNAME --password=$$DB_PASSWORD
        volumes:
            - mysql-vol:/var/lib/mysql
    api:
        build: api
        restart: on-failure
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules/
            - './api:/app/'

    phpMyAdmin:
        depends_on:
            - mysql
        image: phpmyadmin
        restart: on-failure
        ports:
            - "80:80"
        environment:
            - PMA_ARBITRARY=1


volumes:
    mysql-vol:
